name: ci

on:
  push:
    # ignore release branches; See file://./release.yml#on.push.branches , file://./../../.releaserc.ts
    branches-ignore: [main, develop]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  # https://stackoverflow.com/questions/75180149/how-to-cache-dotnet-installation-in-github-actions
  # access to "usr/lib/dotnet" is denied
  DOTNET_INSTALL_DIR: /usr/share/dotnet
  DOTNET_ROOT: /usr/share/dotnet

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0

      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - run: corepack enable
      - name: Setup Node Cache
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install --immutable

      - uses: actions/setup-dotnet@v6

      # if run simultaneously, the logs would be a mess
      - name: Build (Debug)
        run: dotnet build src -c Debug
      # if run simultaneously, the logs would be a mess
      - name: Build (Release)
        run: dotnet build src -c Release

      - name: Publish (Release)
        run: dotnet restore src -t:PublishAll
