name: ci

on:
  push:
    # ignore release branches; See file://./release.yml#on.push.branches , file://./../../.releaserc.ts
    branches-ignore: [main, develop]
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_call:

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  # https://stackoverflow.com/questions/75180149/how-to-cache-dotnet-installation-in-github-actions
  # access to "usr/lib/dotnet" is denied
  DOTNET_INSTALL_DIR: /usr/share/dotnet
  DOTNET_ROOT: /usr/share/dotnet

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          fetch-depth: 0
      - id: isDepUpBranch
        name: Is the current branch a dep-upgrade branch?
        shell: bash
        run: |
          BRANCH_NAME="$(git branch --show-current)"
          echo "BRANCH_NAME is '$BRANCH_NAME'"
          [[ "$BRANCH_NAME" =~ ^(renovate|dependabot)/.+$ ]] &&
            echo $'V=true\nIMMUTABLE_CACHE=--immutable-cache' > $GITHUB_OUTPUT ||
            echo 'This branch is not a dep-upgrade branch.'

      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          cache: yarn
      - run: yarn install --immutable ${{ steps.isDepUpBranch.outputs.IMMUTABLE_CACHE}}

      - uses: actions/setup-dotnet@v5

      # if run simultaneously, the logs would be a mess
      - name: Build (Debug)
        run: dotnet build -c Debug -check
      # if run simultaneously, the logs would be a mess
      - name: Build (Release)
        run: dotnet build -c Release -check

      - name: Publish (Release)
        run: dotnet restore -t:PublishAll
