name: release

on:
  push:
    branches: [main, develop]

env:
  DOTNET_ROLL_FORWARD: Major
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1
  # https://stackoverflow.com/questions/75180149/how-to-cache-dotnet-installation-in-github-actions
  # access to "usr/lib/dotnet" is denied
  DOTNET_INSTALL_DIR: /usr/share/dotnet
  DOTNET_ROOT: /usr/share/dotnet

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
  release:
    name: Release
    # required for proper WPF builds/publishes
    runs-on: windows-latest
    needs: ci
    permissions:
      contents: write # publish a GitHub Release
      issues: write # comment on released issues
      packages: write # push packages to "HaloSPV3" GitHub Nuget Package Registry
      pull-requests: write # comment on released pull requests

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Required by GitVersion, Semantic Release
          submodules: recursive

      - run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
      - run: corepack enable
      - name: Setup Node Cache
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install --immutable

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v6
        with:
          cache: true
          cache-dependency-path: |
            src/packages.lock.json
            src/packages-debug.lock.json

      - name: Semantic Release
        id: semantic-release
        run: yarn release
        env:
          DEBUG: semantic-release*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BuildInParallel: 'false'
